[workspace]
members = ["armory", "bestiary"]

[workspace.package]
version = "1.7.0-alpha.1"
description = "Example game library for Dojo"
edition = "2024_07"
cairo-version = "2.12"
license = "MIT"

[workspace.dependencies]
starknet = "2.12"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.3" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.3" }
