[package]
cairo-version = "=2.11.4"
edition = "2024_07"
name = "types_test"
version = "1.6.0-alpha.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", rev = "4476c33" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", rev = "4476c33" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
